ChromeGaming/Physi-c-Tech

index.html, style.css
I created a new "style.css" file to store all the css files, and shifted the same from "index.html", as it would make the code cleaner and understandle to the users.
Kindly consider my PR under GSSoC '24. Also, kindly label it as GSSoC and assign a level to it.
Thank you!
Fixes #16 
<hr>
<hr>
--- 
<br>
=> Create a new style.css file

style.css
Reverts GameSphere-MultiPlayer/Physi-c-Tech#70
=> Revert "Fixed #61"

Contributing.md
=> Added CONTRIBUTING.md 

game.js, index.html
Hello PA 
Fixed Issue #34 
I have solved the spelling error.
Before-
after i made changes-
please accept this under GSSOC 2024
=> Fixed Issue #34

style.css
The Scroll Bar design is updated
Fixes #85
<hr>
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for review.
<hr>
<br>
=> Scroll bar design is updated

index.html
Added a glowing circle preloader.
Fixes #71 
<hr>
<hr>
https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/154777864/08fbbb98-e666-4235-bef8-d683c1e52e2b
--- 
<br>
**Added Code!**
```
<style>
.preloader {
position: fixed;
top: 0;
left: 0;
width: 100%;
height: 100%;
background: black; 
display: flex;
justify-content: center;
align-items: center;
z-index: 9999; /* Ensure the preloader is above all other content */
}
.circle {
width: 200px; 
height: 200px;
background-color: black;
border-radius: 50%;
animation: circleAnimation 2s infinite linear, glowingBorder 2s infinite linear;
box-shadow: 0 0 20px 10px rgba(255, 0, 0, 0.8); /* Adjusted shadow values */
}
.circle:before {
content: "";
position: absolute;
top: 5px;
left: 5px;
right: 5px;
bottom: 5px;
border-radius: 50%;
border: …
```
=> [New Feature]: Would like to add preloader?

about.html, index.html
Fixed CSS in about page.
And made the website responsive.
Fixes #82 
<hr>
<hr>
--- 
<br>
=> Made the about page more responsive

index.html
In the previous code we are not able to access the website we are only able to see the loading.. but now i have removed that part where the user can use the website now
Fixes #100 
<hr>
- [ x] I have performed a self-review of my own code or work.
<hr>
--- 
<br>
=> The loading in removed

description.js, index.html, style.css
Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
**actual behavior:**
Bug in **Pop-up** box section
Fixes My issue number is #84
<hr>
<hr>
--- 
<br>
**actual behavior:**
Bug in **Pop-up** box section
https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/121508628/3ad3cdf2-f774-42c5-9c33-f8294eb06242
**Expected behavior:**
Fixed Bug in Pop-up box-section and enhancement of pop-up for user friendly
https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/121508628/a095997a-aa1b-4d21-b944-fa15b0c4d07d
**If it still has any issues, please reassign this issue to me and I will fix it better.**
=> [New Feature]: Enhancement the Popup Message

index.html, style.css
Hello @Durgesh4993 
Fixed issue #22
I have made the changes and added buttons .
This is before I made changes.
https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/169278740/01a8fe59-568a-4819-8320-63858413c4b3
This is after I made changes.
Merge the PR and appropriate labels to it .
=> Fixed Issue- #22 : Improving buttons

style.css
I have worked on the CSS files and edited and added the codes where the before and after indexes for the buttons were collapsing with each other and fixed that issue now the buttons doesn't have any overflow of the after effect. I have also implemented button spacing in between (as shown in the image i have attached) to enhance the UI of the website and not making it look congested.
[Bug]: Landing page buttons needs  #107  
<hr>
<hr>
Before ->
After ->
--- 
<br>
=> Enhanced Landing page buttons before and after UI experience

style.css
Reverts GameSphere-MultiPlayer/Physi-c-Tech#117
=> Revert "Enhanced Landing page buttons before and after UI experience"

style.css
Reverts GameSphere-MultiPlayer/Physi-c-Tech#120
=> Revert "Revert "Enhanced Landing page buttons before and after UI experience""

index.html, style.css
Fixed issue:#116
Basically the issue is that home page contents does not have proper style as per the theme. This is not appropriate. Everything present on the website should follow a particular theme.
So for the solution I have choose a good google fonts which is appropriate as per the website.
I have made changes in CSS file.
Add links of google fonts preconnect etc in index.html.
After that I add CSS properties to respective class by inspecting the webpage.
This issue solution basically enhance the overall look of the website.
<hr>
- [ X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) …
=> Home contents style updated

game.js, index.html, style.css
Adding the sound on /off in game page instead of home
Fixes #133 
<hr>
- [x ] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for review.
=> Add Sound in game page

index.html
The git conflict lines from the website has been removed.
Fixes #150 
<hr>
<hr>
=> fix-#150: Git conflict text in website

style.css
Added hover effect on the pantry ingredients and enhanced the scroll bar 
Fixes #154 
<hr>
- [ X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] My changes generates no new warnings.
- [ X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ X] I have added screenshot for review.
<hr>
Added green color …
=> Improved UI of the website

style.css
Fixed the issue of unwanted scrolling on the website which was reducing user experience. Used overflow and max-height properties for the same.
Fixes #152 
<hr>
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md …
=> Removed unwanted scrolling on the website

feedback.html
As soon as the user click on submit feedback option the data is collected, I have added a drop down message that feedback submit successfully for better user experience.
Fixes #162 
- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CON …
=> Enhancing Feedback form (Issue #162)

about.html
Implemented responsiveness in the website page for small screens .
Fixes #167
<hr>
- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for review.
<hr> …
=> Making  Responsive #167

index.html, style.css
Hello @Durgesh4993 
fixed issue : #159
Before changes:
after:
Accept the PR under GSSOC 2024 and add appropriate labels to it.
=> made home page responsive

README.md
##fixes issue #188 
- Added a welcoming project overview
- Detailed the steps for contributing via command line
- Included alternative steps for contributing using GitHub Desktop
- Enhanced the friendly tone to encourage new contributors
This update aims to make the README more comprehensive and inviting for potential contributors.
Revamped README: Making Contributions Easier and More Inviting!
This pull request improves the project's README file with the goal of attracting new contributors and streamlining the contribution process. Here's what's new:
Warm Welcome: added a friendly introduction describing our project's purpose and vision.
Clear Contribution Guide: added detailed steps for contributing using both the command line and GitHub Desktop.
Enhanced Tone:  made the overall tone of …
=> Improve README: Guidelines & Description

about.html
Fixes #144 
The About Page has been updated and now aligns with the main page UI and the feedback page UI. A reference video has been attached.
https://github.com/ChromeGaming/Physi-c-Tech/assets/153659573/06bab8ae-e829-406b-a131-e5287519e888
=> Fixes #144 : Modified About Page

style.css
**Cursor Change:**
When a user hovers over the link text, the cursor should change to a pointer (hand icon) to signify a clickable element.
**Text Styling:**
The link text is styled to resemble a link. Here are the implemented changes:
Hover State:
A subtle underline appears on hover to indicate clickability.
The text colour changes.
Fixes #196 
<hr>
<hr>
https://github.com/ChromeGaming/Physi-c-Tech/assets/146202184/5ccaafdc-4ae9-4a58-b3a1-99e27d8b97b4
--- 
<br>
=> Text Link: Enhance Clickability (Cursor & Styling), Improved link visual on game page

index.html, style.css
This pull request enhances the UI for the Home, Hint, Trash, and Sound buttons in the game page.
* **Improved User Experience:**
By adding hover titles and implementing a subtle hover scaling effect, these changes improve clarity, user experience, and interactivity.
* **Implementation Details:**
Hover titles are implemented using HTML title attributes on the buttons. The hover scaling effect uses a slight increase in button size on mouse hover.
Fixes #193 
<hr>
<hr>
https://github.com/ChromeGaming/Physi-c-Tech/assets/146202184/f2a161ca-f151-4a5f-85f0-5e8bf2f64f75
--- 
<br>
=> Enhance UI for Home, Hint, Trash & Sound buttons

Dockerfile
i add the docker file and also below we write a command through which any user can run this app with the help of docker
Fixes #182 
<hr>
<hr>
--- 
<br>
=> add docker-file

about.html
Added a label of copyright in the footer of about us
Fixes #209 
<hr>
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for review.
<hr>
--- 
<br>
=> added a copyright in the about us page

css/feedback.css, css/style.css, feedback.html, index.html, js/feedback.js
Fixes #221
Issues Solved:
1. Added button on homepage to navigate to the feedback page because before it was not visible.
2. Made the button also responsive
3. Added conformation pop-up message after submission and incorrect message if the fields are not filled properly.
I have added an extra file for it i.e. feedback.js
https://github.com/ChromeGaming/Physi-c-Tech/assets/168854094/89c8718d-82ea-4fb8-a9fe-1612c63a032e
Fixes #221
<hr>
- [ X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [ X] I have commented …
=> Conformation pop-up and navigation to feedback fixed

about.html
1.Added Social Media icons to the website.
2.Hovering effect according to its logo.
3.Linked them the corresponding social media links.
4.Made it responsive for the small screens
Fixes #238
<hr>
<hr>
https://github.com/ChromeGaming/Physi-c-Tech/assets/168854094/f9aa8c00-12fb-4eb4-a150-c02bd4196058
Also made it responsive:
--- 
<br>
=> Added Social Media Icons

about.html
I had enhanced the footer section by aligning the text portion and adding the perfect glow effect as seen in attached screenshot. it is compatible for both mobile and desktop view.
Fixes # <your_issue_number>
Issue no. #242 
Desktop:
Mobile:
=> Enhanced Footer Section

css/feedback.css
Here's a draft for your Pull Request (PR) description:
PR Description 📜
Summary
This PR addresses improvements to the feedback form. The changes include reducing the dimensions of the feedback form, adding floating text animations, and modifying the text to enhance user experience.
Fixes #42
<hr>
Mark the task you have completed ✅
I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
I have performed a self-review of my own code or work.
I have commented my code, particularly in hard-to-understand areas.
My changes generate no new warnings.
I have followed proper naming …
=> added floating animation in feedback form and fixed its dimension for better ui ux 

README.md
Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # 263
<hr>
<hr>
--- 
<br>
=> Added cd Physi-c-Tech

README.md
Added Contributors page in README.md to display profiles of all the contributors.
Fixes #258
<hr>
<hr>
--- 
<br>
=> Added Contributors page in README.md

howtoplay.html, index.html
Added how To play button Which can help the user to find the how to play soon.
Fixes #268 
<hr>
<hr>
--- 
<br>
=> added How to play button
